version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: placeholder
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/placeholder
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: bXlDdXN0b21TZWNyZXRLZXlGb3JKc3duSldUU2VjcmV0S2V5Rm9ySldU
      JWT_EXPIRATION: 86400000
    depends_on:
      - db 